version: '3'

services:
    web:
        container_name: tz_web
        image: nginx
        volumes:
            - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
            - ./logs/nginx:/var/log/nginx
        ports:
            - "8081:8081"
        depends_on:
            - php

    php:
        container_name: tz_php
        build: conf
        volumes:
            - ./conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./:/var/www/html

    postgres:
        container_name: tz_postgres
        image: postgres:14.2-alpine
        environment:
            POSTGRES_USER: tzuser
            POSTGRES_PASSWORD: HCK6LreUsVu63ZdF
            POSTGRES_DB: tz_db
        ports:
            - "5432:5432"
        volumes:
            - ./data/postgres/pg_data:/var/lib/postgresql/data
            - ./data/postgres/dumps:/tmp/
            - ./conf/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
